service: python-service

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: python3.9

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: time
          method: get
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-openwhisk
