service: swift-packages

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: swift

functions:
  hello:
    handler: .build/release/hello
    tags:
      git_org: ghouldaemon
  welcome:
    handler: .build/release/welcome
    tags:
      git_org: ghouldaemon

custom:
  scripts:
    hooks:
      'package:initialize': npm run-script compile
plugins:
  - serverless-openwhisk
  - serverless-plugin-scripts
