service: aws-python-flask-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-wsgi
  - serverless-python-requirements
