service: aws-python-sqs-worker
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer

functions:
  producer:
    handler: handler.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-lift
  - serverless-python-requirements

package:
  patterns:
    - "!node_modules/**"
