service: serverless-http-api-mongodb

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

functions:
  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /user
          method: post
    tags:
      git_org: ghouldaemon
  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /user/{id}
          method: put
    tags:
      git_org: ghouldaemon
  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete
    tags:
      git_org: ghouldaemon
  user:
    handler: handler.user
    events:
      - httpApi:
          path: /user/{id}
          method: get
    tags:
      git_org: ghouldaemon
