service: serverless-http-api-pynamodb
frameworkVersion: "3"

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.9
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: todos/create.create
    events:
      - httpApi:
          path: /todos
          method: post
    tags:
      git_org: ghouldaemon
  list:
    handler: todos/list.todo_list
    events:
      - httpApi:
          path: /todos
          method: get
    tags:
      git_org: ghouldaemon
  get:
    handler: todos/get.get
    events:
      - httpApi:
          path: /todos/{id}
          method: get
    tags:
      git_org: ghouldaemon
  update:
    handler: todos/update.update
    events:
      - httpApi:
          path: /todos/{todo_id}
          method: put
    tags:
      git_org: ghouldaemon
  delete:
    handler: todos/delete.delete
    events:
      - httpApi:
          path: /todos/{todo_id}
          method: delete
    tags:
      git_org: ghouldaemon

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: todo_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: todo_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
