service: python-service

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: python3.9

functions:
  greeting:
    handler: handler.endpoint
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-openwhisk
