service: swift-service

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: swift

functions:
  ping:
    handler: ping.main
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-openwhisk
