service:
  name: aws-nodejs-ecma-script
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x

functions:
  first:
    handler: first.hello
    tags:
      git_org: ghouldaemon
  second:
    handler: second.hello
    events:
      - httpApi:
          method: get
          path: /second
    tags:
      git_org: ghouldaemon
