service: aws-node-rest-api-typescript

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: books
          method: post
    tags:
      git_org: ghouldaemon
  update:
    handler: app/handler.update
    events:
      - http:
          path: books/{id}
          method: put
    tags:
      git_org: ghouldaemon
  find:
    handler: app/handler.find
    events:
      - http:
          path: books
          method: get
    tags:
      git_org: ghouldaemon
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: books/{id}
          method: get
    tags:
      git_org: ghouldaemon
  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: books/{id}
          method: delete
    tags:
      git_org: ghouldaemon
