service: aws-node-rest-api-mongodb

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
    tags:
      git_org: ghouldaemon
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true
    tags:
      git_org: ghouldaemon
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
    tags:
      git_org: ghouldaemon
  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
    tags:
      git_org: ghouldaemon
