service: function-with-environment-variables

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    EMAIL_SERVICE_API_KEY: KEYEXAMPLE1234

functions:
  createUser:
    handler: handler.createUser
    environment:
      PASSWORD_ITERATIONS: 4096
      PASSWORD_DERIVED_KEY_LENGTH: 256
    tags:
      git_org: ghouldaemon
  resetPassword:
    handler: handler.resetPassword
    tags:
      git_org: ghouldaemon
