service: hellotime-app
provider:
  name: aws

functions:
  hello:
    runtime: python3.9
    events:
      - httpApi:
          method: get
          path: /greet
    handler: web/handler.hello
    tags:
      git_org: ghouldaemon
  time:
    runtime: nodejs12.x
    events:
      - httpApi:
          method: get
          path: /time
    handler: api/handler.timestamp
    tags:
      git_org: ghouldaemon
