service: ruby-service

frameworkVersion: "3"

provider:
  name: openwhisk
  runtime: ruby2.7

functions:
  greeting:
    handler: handler.main
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-openwhisk
