service: aws-node-typescript # NOTE: update this with your service name
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    tags:
      git_org: ghouldaemon

plugins:
  - serverless-esbuild
