service: aws-node-ses-receive-email-header

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  processheader:
    handler: handler.processheader
    tags:
      git_org: ghouldaemon
  processacceptreject:
    handler: handler.processacceptreject
    tags:
      git_org: ghouldaemon

resources:
  Resources:
    GiveSESPermissionToInvokeProcessheaderLambdaFunction:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: { "Fn::GetAtt": [ "ProcessheaderLambdaFunction", "Arn" ] }
        Principal: ses.amazonaws.com
        Action: 'lambda:InvokeFunction'
        SourceAccount: { Ref: AWS::AccountId }
    GiveSESPermissionToInvokeProcessacceptrejectLambdaFunction:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: { "Fn::GetAtt": [ "ProcessacceptrejectLambdaFunction", "Arn" ] }
        Principal: ses.amazonaws.com
        Action: 'lambda:InvokeFunction'
        SourceAccount: { Ref: AWS::AccountId }
